//! # dioxus-nox-cycle
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Generic hook for cycling through an ordered set of values.
//!
//! Useful for set type toggles, status cycles, priority selectors, or any
//! ordered enum. Could also live in a future `dioxus-nox-primitives` collection.
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_cycle::*;
//!
//! #[derive(Clone, PartialEq)]
//! enum Priority { Low, Medium, High }
//!
//! #[component]
//! fn PriorityToggle() -> Element {
//!     let cycle = use_cycle(&[Priority::Low, Priority::Medium, Priority::High], None);
//!
//!     rsx! {
//!         button {
//!             onclick: move |_| cycle.next.call(()),
//!             match *cycle.current.read() {
//!                 Priority::Low => "Low",
//!                 Priority::Medium => "Medium",
//!                 Priority::High => "High",
//!             }
//!         }
//!     }
//! }
//! ```

mod hook;
mod types;

#[cfg(test)]
mod tests;

pub use hook::use_cycle;
pub use types::CycleState;
