//! # dioxus-nox-scheduler
//!
//! **Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk.
//!
//! Headless scheduling/event primitives for Dioxus applications.
//!
//! Provides day/week/agenda views with event overlap layout, keyboard
//! navigation, and data attributes for styling — shipping **zero visual
//! styles**. Complements (not replaces) the official dioxus-primitives calendar.
//!
//! ## Features
//!
//! - **Day view** — single-day timeline with hour/half-hour slots
//! - **Week view** — 7-day side-by-side layout
//! - **Agenda view** — flat chronological event list
//! - **Event overlap layout** — column-packing algorithm for overlapping events
//! - **Keyboard navigation** — arrow keys between slots/days, Enter/Space to select
//! - **Event selection** — `data-selected` attribute on events
//! - **Drag-to-move/resize** via `dioxus-nox-dnd` (feature `dnd`)
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_scheduler::*;
//!
//! #[component]
//! fn App() -> Element {
//!     rsx! {
//!         scheduler::Root {
//!             view: SchedulerView::Week,
//!             scheduler::Header {
//!                 scheduler::PrevButton { "←" }
//!                 scheduler::Title {}
//!                 scheduler::NextButton { "→" }
//!             }
//!             scheduler::WeekView {
//!                 scheduler::TimeGrid {
//!                     scheduler::TimeSlot { date: today, hour: 9, minute: 0 }
//!                     scheduler::Event { event_id: "meeting-1", "Team standup" }
//!                 }
//!             }
//!         }
//!     }
//! }
//! ```

mod components;
pub mod layout;
pub mod navigation;
mod types;

#[cfg(test)]
mod tests;

pub use layout::{compute_event_layout, LayoutEvent};
pub use navigation::{
    navigate_slot, next_day, next_week, prev_day, prev_week, week_dates, week_start, SlotDirection,
};
pub use types::{
    EventDropData, EventEntry, EventPosition, EventResizeData, ScheduleEvent, SchedulerContext,
    SchedulerView, TimeSlotData,
};

/// Compound component namespace.
///
/// ```rust,ignore
/// scheduler::Root { scheduler::Header { .. } scheduler::DayView { .. } }
/// ```
pub mod scheduler {
    pub use crate::components::{
        AgendaDay, AgendaEvent, AgendaView, AllDayRow, DayView, Event, Header, NextButton,
        PrevButton, Root, TimeGrid, TimeSlot, Title, TodayButton, WeekView,
    };
}
