//! # dioxus-nox-toggle-group
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Headless toggle group / segmented control with ARIA radiogroup semantics.
//!
//! Supports single-select (radiogroup) and multi-select (group) modes with
//! full keyboard navigation (Arrow keys, Home, End, Space/Enter).
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_toggle_group::*;
//!
//! #[component]
//! fn FilterBar() -> Element {
//!     let mut active = use_signal(|| "all".to_string());
//!
//!     rsx! {
//!         toggle_group::Root {
//!             value: (*active.read()).clone(),
//!             on_value_change: move |v: String| active.set(v),
//!             toggle_group::Item { value: "all".to_string(), "All" }
//!             toggle_group::Item { value: "active".to_string(), "Active" }
//!             toggle_group::Item { value: "done".to_string(), "Done" }
//!         }
//!     }
//! }
//! ```
//!
//! ## ARIA attributes
//!
//! | Attribute | Component | Value |
//! |-----------|-----------|-------|
//! | `role` | Root | `"radiogroup"` (single) or `"group"` (multi) |
//! | `aria-orientation` | Root | `"horizontal"` \| `"vertical"` |
//! | `role` | Item | `"radio"` (single) or `"checkbox"` (multi) |
//! | `aria-checked` | Item | `"true"` \| `"false"` |
//! | `data-state` | Item | `"on"` \| `"off"` |
//! | `data-disabled` | Item | present when disabled |

mod components;
mod types;

#[cfg(test)]
mod tests;

pub use types::{Orientation, ToggleGroupContext};

/// Compound component namespace.
pub mod toggle_group {
    pub use crate::components::{Item, Root};
}
