//! # dioxus-nox-drawer
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Headless drawer/sheet primitive that slides from any edge.
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_drawer::*;
//!
//! #[component]
//! fn App() -> Element {
//!     let mut open = use_signal(|| false);
//!
//!     rsx! {
//!         button { onclick: move |_| open.set(true), "Open Drawer" }
//!         drawer::Root {
//!             open: *open.read(),
//!             on_close: move |_| open.set(false),
//!             side: DrawerSide::Right,
//!             drawer::Overlay {}
//!             drawer::Content {
//!                 h2 { "Drawer content" }
//!             }
//!         }
//!     }
//! }
//! ```
//!
//! ## Data attributes
//!
//! | Attribute | Component | Values |
//! |-----------|-----------|--------|
//! | `data-state` | Root, Content | `"open"` \| `"closed"` |
//! | `data-side` | Content | `"left"` \| `"right"` \| `"bottom"` \| `"top"` |

mod components;
mod types;

#[cfg(test)]
mod tests;

pub use types::{DrawerContext, DrawerSide};

/// Compound component namespace.
///
/// ```rust,ignore
/// drawer::Root { drawer::Overlay {} drawer::Content { .. } }
/// ```
pub mod drawer {
    pub use crate::components::{Content, Overlay, Root};
}
