//! # dioxus-nox-toast
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Headless toast notification system with queue management and auto-dismiss.
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_toast::*;
//!
//! #[component]
//! fn App() -> Element {
//!     let mut manager = use_toast_manager::<String>(3);
//!
//!     rsx! {
//!         button {
//!             onclick: move |_| {
//!                 manager.show("Hello!".to_string(), std::time::Duration::from_secs(5));
//!             },
//!             "Show Toast"
//!         }
//!         ToastViewport {
//!             render_toast: |toast: Toast<String>| {
//!                 rsx! { div { "{toast.data}" } }
//!             }
//!         }
//!     }
//! }
//! ```

mod components;
mod hook;
mod manager;
mod types;

#[cfg(test)]
mod tests;

pub(crate) mod time {
    #[cfg(target_arch = "wasm32")]
    pub(crate) fn now_ms() -> i64 {
        js_sys::Date::now() as i64
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub(crate) fn now_ms() -> i64 {
        use std::time::{SystemTime, UNIX_EPOCH};
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64
    }

    #[cfg(target_arch = "wasm32")]
    pub(crate) async fn sleep_ms(ms: u32) {
        gloo_timers::future::TimeoutFuture::new(ms).await;
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub(crate) async fn sleep_ms(ms: u32) {
        tokio::time::sleep(std::time::Duration::from_millis(ms as u64)).await;
    }
}

pub use components::ToastViewport;
pub use hook::use_toast_manager;
pub use manager::ToastManager;
pub use types::{Toast, ToastId};
