//! # dioxus-nox-modal
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Headless modal dialog primitive for Dioxus with focus trap, scroll lock, and ARIA.
//!
//! ## Layers
//!
//! | Layer | Items | Dioxus dependency? |
//! |-------|-------|--------------------|
//! | **Types** | [`ModalContext`], [`ModalHandle`] | Yes (Signals) |
//! | **Hook** | [`use_modal`] | Yes (Signals, Callbacks) |
//! | **Components** | [`modal::Root`], [`modal::Overlay`], [`modal::Content`] | Yes (RSX, context) |
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_modal::*;
//!
//! #[component]
//! fn App() -> Element {
//!     let handle = use_modal(false);
//!
//!     rsx! {
//!         button { onclick: move |_| handle.show.call(()), "Open Modal" }
//!         modal::Root {
//!             open: *handle.open.read(),
//!             on_close: move |_| handle.close.call(()),
//!             modal::Overlay {}
//!             modal::Content {
//!                 h2 { "Hello from modal!" }
//!                 button { onclick: move |_| handle.close.call(()), "Close" }
//!             }
//!         }
//!     }
//! }
//! ```
//!
//! ## Data attributes
//!
//! | Attribute | Component | Values |
//! |-----------|-----------|--------|
//! | `data-state` | Root, Content | `"open"` \| `"closed"` |
//!
//! ## ARIA attributes
//!
//! | Attribute | Component | Value |
//! |-----------|-----------|-------|
//! | `role` | Content | `"dialog"` |
//! | `aria-modal` | Content | `"true"` |
//! | `aria-labelledby` | Content | auto-generated ID |
//! | `aria-hidden` | Overlay | `"true"` |

mod components;
mod hook;
mod types;

#[cfg(test)]
mod tests;

pub use hook::use_modal;
pub use types::{ModalContext, ModalHandle};

/// Compound component namespace.
///
/// ```rust,ignore
/// modal::Root { modal::Overlay {} modal::Content { .. } }
/// ```
pub mod modal {
    pub use crate::components::{Content, Overlay, Root};
}
