//! # dioxus-nox-master-detail
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Headless master-detail layout with responsive breakpoint awareness.
//!
//! - Mobile: detail opens as full-screen overlay
//! - Tablet: detail opens as right-side panel
//! - Desktop: detail renders inline as sidebar
//!
//! All responsive behavior is driven by `data-*` attributes — consumers
//! apply their own CSS via attribute selectors.
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_master_detail::*;
//!
//! #[component]
//! fn App() -> Element {
//!     let mut detail_open = use_signal(|| false);
//!
//!     rsx! {
//!         master_detail::Root {
//!             detail_open: *detail_open.read(),
//!             on_detail_close: move |_| detail_open.set(false),
//!             master_detail::Master {
//!                 button { onclick: move |_| detail_open.set(true), "Open Detail" }
//!             }
//!             master_detail::Detail {
//!                 p { "Detail content here" }
//!             }
//!         }
//!     }
//! }
//! ```
//!
//! ## Data attributes
//!
//! | Attribute | Component | Values |
//! |-----------|-----------|--------|
//! | `data-detail` | Root | `"open"` \| `"closed"` |

mod components;
mod types;

#[cfg(test)]
mod tests;

pub use types::MasterDetailContext;

/// Compound component namespace.
pub mod master_detail {
    pub use crate::components::{Backdrop, Detail, Master, Root};
}
