//! # dioxus-nox-virtualize
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Viewport math for virtual scrolling lists with fixed-height items.
//!
//! This crate provides pure, testable viewport calculations that can be
//! used to implement virtual list rendering in Dioxus or any other framework.
//!
//! ## Usage
//!
//! ```rust
//! use dioxus_nox_virtualize::VirtualViewport;
//!
//! let mut vp = VirtualViewport::new(1000, 40, 400);
//! vp.scroll_top = 800;
//!
//! let (start, end) = vp.visible_range();
//! // Renders items start..end, with spacers for the rest
//! let top_spacer = vp.top_spacer_height();
//! let bottom_spacer = vp.bottom_spacer_height();
//! ```

mod viewport;
mod variable_viewport;

#[cfg(feature = "hooks")]
mod hook;

#[cfg(feature = "component")]
mod component;

pub use viewport::VirtualViewport;
pub use variable_viewport::VariableViewport;

#[cfg(feature = "hooks")]
pub use hook::*;

#[cfg(feature = "component")]
pub mod virtual_list {
    //! Compound component for virtual lists with variable-height items.
    //!
    //! See [`Root`], [`Viewport`], [`Item`], and [`use_visible_range`].
    pub use crate::component::{Item, Root, Viewport, VirtualListContext, use_visible_range};
}

#[cfg(test)]
mod tests {
    use crate::VirtualViewport;

    #[test]
    fn visible_range_at_top() {
        let vp = VirtualViewport::new(100, 40, 400);
        let (start, end) = vp.visible_range();
        assert_eq!(start, 0); // clamped by overscan
        // visible = 400/40 = 10 items + overscan 5 on each side + 1 = 16 total from 0
        assert!(end <= 100);
        assert!(end >= 10); // at least visible items
    }

    #[test]
    fn visible_range_mid_scroll() {
        let mut vp = VirtualViewport::new(100, 40, 400);
        vp.scroll_top = 2000; // scroll to item 50
        let (start, end) = vp.visible_range();
        // first_visible = 2000/40 = 50, start = 50-5=45
        assert_eq!(start, 45);
        // end = 50 + ceil(400/40) + 5 + 1 = 50 + 10 + 6 = 66
        assert!(end > start);
        assert!(end <= 100);
    }

    #[test]
    fn visible_range_overscan_clamp() {
        // At scroll_top=0, start should be 0 (not negative)
        let vp = VirtualViewport {
            item_count: 20,
            item_height: 40,
            viewport_height: 200,
            scroll_top: 0,
            overscan: 10,
        };
        let (start, _) = vp.visible_range();
        assert_eq!(start, 0);
    }

    #[test]
    fn visible_range_end_clamp() {
        // Near end of list, end should not exceed item_count
        let mut vp = VirtualViewport::new(10, 40, 400);
        vp.scroll_top = 0;
        let (_, end) = vp.visible_range();
        assert!(end <= 10);
    }

    #[test]
    fn visible_range_empty_list() {
        let vp = VirtualViewport::new(0, 40, 400);
        assert_eq!(vp.visible_range(), (0, 0));
    }

    #[test]
    fn visible_range_zero_item_height() {
        let vp = VirtualViewport::new(100, 0, 400);
        assert_eq!(vp.visible_range(), (0, 0));
    }

    #[test]
    fn total_height() {
        let vp = VirtualViewport::new(100, 40, 400);
        assert_eq!(vp.total_height(), 4000);
    }

    #[test]
    fn total_height_empty() {
        let vp = VirtualViewport::new(0, 40, 400);
        assert_eq!(vp.total_height(), 0);
    }

    #[test]
    fn offset_for_idx() {
        let vp = VirtualViewport::new(100, 40, 400);
        assert_eq!(vp.offset_for_idx(0), 0);
        assert_eq!(vp.offset_for_idx(5), 200);
        assert_eq!(vp.offset_for_idx(10), 400);
    }

    #[test]
    fn top_spacer_at_top() {
        let vp = VirtualViewport::new(100, 40, 400);
        // At top, start=0, spacer=0
        assert_eq!(vp.top_spacer_height(), 0);
    }

    #[test]
    fn top_spacer_mid_scroll() {
        let mut vp = VirtualViewport::new(100, 40, 400);
        vp.scroll_top = 2000; // first_visible=50, start=45
        let top = vp.top_spacer_height();
        assert_eq!(top, 45 * 40); // 1800px
    }

    #[test]
    fn bottom_spacer_near_end() {
        let mut vp = VirtualViewport::new(100, 40, 400);
        vp.scroll_top = 3600; // near end
        let bottom = vp.bottom_spacer_height();
        // Should be small, rendering near-end items
        assert!(bottom < 400);
    }

    #[test]
    fn default_viewport() {
        let vp = VirtualViewport::default();
        assert_eq!(vp.item_height, 40);
        assert_eq!(vp.overscan, 5);
        assert_eq!(vp.scroll_top, 0);
    }

    #[test]
    fn clone_and_partial_eq() {
        let vp1 = VirtualViewport::new(50, 30, 300);
        let vp2 = vp1.clone();
        assert_eq!(vp1, vp2);
    }

    #[test]
    fn is_near_end_empty_list() {
        let vp = VirtualViewport::new(0, 40, 400);
        assert!(!vp.is_near_end(5));
    }

    #[test]
    fn is_near_end_single_item() {
        let vp = VirtualViewport::new(1, 40, 400);
        // Entire list visible, 1 + 5 >= 1 → true
        assert!(vp.is_near_end(5));
    }

    #[test]
    fn is_near_end_exactly_at_threshold() {
        let mut vp = VirtualViewport::new(100, 40, 400);
        // Scroll far enough that visible end is within threshold of item_count
        vp.scroll_top = 80 * 40; // first_visible=80, end clamped to 100
        assert!(vp.is_near_end(5));
    }

    #[test]
    fn is_near_end_beyond_threshold() {
        let vp = VirtualViewport::new(100, 40, 400);
        // At top: end ≈ 16, threshold=5: 16+5=21 < 100 → false
        assert!(!vp.is_near_end(5));
    }
}
