//! # dioxus-nox-datagrid
//!
//! **Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk.
//!
//! Headless interactive data grid primitives for Dioxus applications.
//!
//! Follows the Radix compound component pattern with proper ARIA roles,
//! keyboard navigation, and data attributes for styling — shipping **zero
//! visual styles**.
//!
//! ## Features
//!
//! - **Column definitions** with sortable, resizable, editable, and pinnable options
//! - **Row selection** (none, single, multi) via `data-selected` attributes
//! - **Cell-level keyboard navigation** (arrow keys, Home/End, Ctrl+Home/End)
//! - **Inline cell editing** (text, number, select, custom editors)
//! - **Column resizing** via pointer drag handles
//! - **Column reordering** via `dioxus-nox-dnd` (feature `dnd`)
//! - **Virtual scrolling** via `dioxus-nox-virtualize` (feature `virtualize`)
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_datagrid::*;
//!
//! #[component]
//! fn App() -> Element {
//!     rsx! {
//!         datagrid::Root {
//!             columns: vec![
//!                 ColumnDef::new("name").header("Name").sortable(true),
//!                 ColumnDef::new("value").header("Value"),
//!             ],
//!             datagrid::Header {
//!                 datagrid::HeaderRow {
//!                     datagrid::HeaderCell { col_index: 0, "Name" }
//!                     datagrid::HeaderCell { col_index: 1, "Value" }
//!                 }
//!             }
//!             datagrid::Body {
//!                 datagrid::Row { row_id: "1", row_index: 0,
//!                     datagrid::Cell { row_id: "1", row_index: 0, col_index: 0, "Alice" }
//!                     datagrid::Cell { row_id: "1", row_index: 0, col_index: 1, "100" }
//!                 }
//!             }
//!         }
//!     }
//! }
//! ```
//!
//! ## Data attributes
//!
//! | Attribute | Component | Values |
//! |-----------|-----------|--------|
//! | `data-grid-state` | Root | `"idle"` \| `"editing"` \| `"selecting"` |
//! | `data-sort` | HeaderCell | `"asc"` \| `"desc"` |
//! | `data-resizable` | HeaderCell | `"true"` |
//! | `data-pinned` | HeaderCell, Cell | `"left"` \| `"right"` |
//! | `data-selected` | Row | `"true"` |
//! | `data-focused` | Cell | `"true"` |
//! | `data-editing` | Cell | `"true"` |
//! | `data-disabled` | Row, Cell | `"true"` |
//! | `data-col-index` | HeaderCell, Cell | column index |
//! | `data-row-index` | Row | row index |

mod components;
mod context;
mod editing;
mod navigation;
mod types;

#[cfg(test)]
mod tests;

// Re-export types at crate root.
pub use context::DataGridContext;
pub use editing::EditState;
pub use navigation::{navigate_grid, GridNavKey};
pub use types::{
    CellCoord, CellEditEvent, CellEditor, ColumnDef, GridState, PinSide, RenderCell, RowData,
    RowEntry, Selection, SortDirection, SortState,
};

/// Compound component namespace.
///
/// ```rust,ignore
/// datagrid::Root { datagrid::Header { .. } datagrid::Body { .. } }
/// ```
pub mod datagrid {
    pub use crate::components::{Body, Cell, Header, HeaderCell, HeaderRow, ResizeHandle, Root, Row};
}
