//! # dioxus-nox-inline-confirm
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Headless inline confirmation pattern.
//!
//! Replaces a destructive action trigger with confirm/cancel buttons inline.
//! Two-phase UI: Idle shows the trigger, Confirming shows confirm/cancel.
//!
//! ## Quick start
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_inline_confirm::*;
//!
//! #[component]
//! fn DeleteButton() -> Element {
//!     let handle = use_inline_confirm(Some(5000)); // auto-cancel after 5s
//!
//!     rsx! {
//!         inline_confirm::Root {
//!             state: *handle.state.read(),
//!             on_confirm: move |_| { /* delete item */ },
//!             on_cancel: move |_| {},
//!             inline_confirm::Trigger {
//!                 button { onclick: move |_| handle.request.call(()), "Delete" }
//!             }
//!             inline_confirm::Action {
//!                 button { onclick: move |_| handle.confirm.call(()), "Confirm" }
//!                 button { onclick: move |_| handle.cancel.call(()), "Cancel" }
//!             }
//!         }
//!     }
//! }
//! ```
//!
//! ## Data attributes
//!
//! | Attribute | Component | Values |
//! |-----------|-----------|--------|
//! | `data-state` | Root | `"idle"` \| `"confirming"` |

mod components;
mod hook;
mod types;

#[cfg(test)]
mod tests;

pub use hook::use_inline_confirm;
pub use types::{ConfirmState, InlineConfirmContext, InlineConfirmHandle};

/// Compound component namespace.
pub mod inline_confirm {
    pub use crate::components::{Action, Root, Trigger};
}
