//! # dioxus-nox
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Umbrella crate for the **dioxus-nox** headless component library.
//!
//! Enable individual crates via feature flags:
//!
//! ```toml
//! [dependencies]
//! dioxus-nox = { version = "0.13", features = ["cmdk", "markdown"] }
//! ```
//!
//! Or enable everything:
//!
//! ```toml
//! [dependencies]
//! dioxus-nox = { version = "0.13", features = ["full"] }
//! ```

#[cfg(feature = "cmdk")]
pub use dioxus_nox_cmdk as cmdk;

#[cfg(feature = "dnd")]
pub use dioxus_nox_dnd as dnd;

#[cfg(feature = "markdown")]
pub use dioxus_nox_markdown as markdown;

#[cfg(feature = "shell")]
pub use dioxus_nox_shell as shell;

#[cfg(feature = "suggest")]
pub use dioxus_nox_suggest as suggest;

#[cfg(feature = "tag-input")]
pub use dioxus_nox_tag_input as tag_input;

#[cfg(feature = "virtualize")]
pub use dioxus_nox_virtualize as virtualize;

#[cfg(feature = "preview")]
pub use dioxus_nox_preview as preview;

#[cfg(feature = "extensions")]
pub use dioxus_nox_extensions as extensions;

#[cfg(feature = "gestures")]
pub use dioxus_nox_gestures as gestures;

#[cfg(feature = "tabs")]
pub use dioxus_nox_tabs as tabs;

#[cfg(feature = "timer")]
pub use dioxus_nox_timer as timer;

#[cfg(feature = "modal")]
pub use dioxus_nox_modal as modal;

#[cfg(feature = "drawer")]
pub use dioxus_nox_drawer as drawer;

#[cfg(feature = "toast")]
pub use dioxus_nox_toast as toast;

#[cfg(feature = "master-detail")]
pub use dioxus_nox_master_detail as master_detail;

#[cfg(feature = "cycle")]
pub use dioxus_nox_cycle as cycle;

#[cfg(feature = "inline-confirm")]
pub use dioxus_nox_inline_confirm as inline_confirm;

#[cfg(feature = "toggle-group")]
pub use dioxus_nox_toggle_group as toggle_group;

#[cfg(feature = "password-strength")]
pub use dioxus_nox_password_strength as password_strength;

#[cfg(feature = "select")]
pub use dioxus_nox_select as select;

#[cfg(feature = "collection")]
pub use dioxus_nox_collection as collection;

/// Convenience re-exports of the most commonly used types.
///
/// ```rust,ignore
/// use dioxus_nox::prelude::*;
/// ```
pub mod prelude {
    #[cfg(feature = "cmdk")]
    pub use dioxus_nox_cmdk::{
        CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList,
        CommandPalette, use_command_palette,
    };

    #[cfg(feature = "dnd")]
    pub use dioxus_nox_dnd::prelude::{
        ActiveDrag, AnnouncementEvent, CollisionStrategy, DragContext, DragContextProvider,
        DragData, DragId, DragOverlay, DragState, DragType, Draggable, DropEvent, DropIndicator,
        DropLocation, DropZone, DropZoneState, IndicatorPosition, MergeEvent, MoveEvent,
        Orientation as DndOrientation, Position, Rect, ReorderEvent, SortableContext,
        SortableGroup, SortableItem, SortableItemState,
    };

    #[cfg(feature = "markdown")]
    pub use dioxus_nox_markdown::prelude::{
        Mode, Orientation as MarkdownOrientation, highlight_code, parse_document,
        use_markdown_context, use_markdown_handle,
    };

    #[cfg(feature = "shell")]
    pub use dioxus_nox_shell::{AppShell, ShellContext, use_shell_breakpoint, use_shell_context};

    #[cfg(feature = "suggest")]
    pub use dioxus_nox_suggest::{TriggerConfig, TriggerSelectEvent, suggest, use_suggestion};

    #[cfg(feature = "tag-input")]
    pub use dioxus_nox_tag_input::{use_tag_input, use_tag_input_grouped};

    #[cfg(feature = "virtualize")]
    pub use dioxus_nox_virtualize::VirtualViewport;

    #[cfg(feature = "preview")]
    pub use dioxus_nox_preview::{
        PreviewPosition, preview, use_debounced_active, use_preview_cache,
    };

    #[cfg(feature = "extensions")]
    pub use dioxus_nox_extensions::{Extension, PluginCommand, use_extensions};

    #[cfg(feature = "gestures")]
    pub use dioxus_nox_gestures::{SwipeConfig, swipe_actions, use_long_press, use_swipe_gesture};

    #[cfg(feature = "tabs")]
    pub use dioxus_nox_tabs::{ActivationMode, Orientation as TabsOrientation, tabs};

    #[cfg(feature = "timer")]
    pub use dioxus_nox_timer::{
        CountdownControls, TimerState, format_duration, use_countdown, use_stopwatch,
    };

    #[cfg(feature = "modal")]
    pub use dioxus_nox_modal::{ModalHandle, modal, use_modal};

    #[cfg(feature = "drawer")]
    pub use dioxus_nox_drawer::{DrawerSide, drawer};

    #[cfg(feature = "toast")]
    pub use dioxus_nox_toast::{Toast, ToastId, ToastManager, ToastViewport, use_toast_manager};

    #[cfg(feature = "master-detail")]
    pub use dioxus_nox_master_detail::master_detail;

    #[cfg(feature = "cycle")]
    pub use dioxus_nox_cycle::{CycleState, use_cycle};

    #[cfg(feature = "inline-confirm")]
    pub use dioxus_nox_inline_confirm::{
        ConfirmState, InlineConfirmHandle, inline_confirm, use_inline_confirm,
    };

    #[cfg(feature = "toggle-group")]
    pub use dioxus_nox_toggle_group::{Orientation as ToggleGroupOrientation, toggle_group};

    #[cfg(feature = "password-strength")]
    pub use dioxus_nox_password_strength::{
        StrengthLevel, StrengthResult, assess_password_strength_default,
    };

    #[cfg(feature = "select")]
    pub use dioxus_nox_select::{AutoComplete, CustomFilter, SelectContext, select};

    #[cfg(feature = "collection")]
    pub use dioxus_nox_collection::{ListItem, ScoringStrategy};
}
