//! # dioxus-nox-password-strength
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Pure-logic password strength assessment with optional Dioxus hook.
//!
//! The core function [`assess_password_strength`] has **zero Dioxus dependency**
//! and can be used in CLI tools, server-side validation, or any Rust context.
//!
//! ## Usage (pure function)
//!
//! ```rust
//! use dioxus_nox_password_strength::*;
//!
//! let result = assess_password_strength_default("MyP@ssw0rd!");
//! assert!(result.score >= 3);
//! assert_eq!(result.level, StrengthLevel::Strong);
//! ```
//!
//! ## Usage (Dioxus hook)
//!
//! ```rust,ignore
//! use dioxus::prelude::*;
//! use dioxus_nox_password_strength::*;
//!
//! #[component]
//! fn PasswordField() -> Element {
//!     let password = use_signal(|| String::new());
//!     let strength = use_password_strength(password);
//!
//!     rsx! {
//!         input { oninput: move |e| password.set(e.value()) }
//!         // Consumer builds their own UI (bars, text, colors):
//!         div {
//!             role: "meter",
//!             aria_valuenow: "{strength.read().score}",
//!             aria_valuemin: "0",
//!             aria_valuemax: "4",
//!             aria_label: "Password strength",
//!             "{strength.read().label}"
//!         }
//!     }
//! }
//! ```

mod assess;
mod types;

#[cfg(feature = "dioxus")]
mod hook;

#[cfg(test)]
mod tests;

pub use assess::{assess_password_strength, assess_password_strength_default, default_checks};
#[cfg(feature = "dioxus")]
pub use hook::{use_password_strength, use_password_strength_with};
pub use types::{StrengthCheck, StrengthLevel, StrengthResult};
