//! # dioxus-nox-core
//!
//! **⚠️ Disclaimer:** This crate was entirely generated by AI (Claude) as part of a
//! personal learning project. It has not been battle-tested in production and may
//! contain bugs or unsound abstractions. Use at your own risk and exercise extreme
//! caution before depending on it in anything that matters.
//!
//! Core utilities for dioxus-nox overlay crates (modal, drawer, cmdk).
//!
//! Provides:
//! - Focus trap helpers (Tab/Shift+Tab cycling within a container)
//! - Scroll lock (body overflow toggling)
//! - Background inert management (marking siblings as `inert`)
//!
//! All functions are cross-platform with wasm32-specific implementations
//! and no-op stubs for desktop/mobile targets.

pub mod focus_trap;
pub mod inert;
pub mod scroll_lock;

#[cfg(test)]
mod tests;

pub use focus_trap::{cycle_focus, get_focusable_elements_in_container};
pub use inert::set_siblings_inert;
pub use scroll_lock::{lock_body_scroll, unlock_body_scroll};
